#!/bin/bash

function usage() {
	cat - <<EOF
	wiki [-u <USERNAME> -p <PASSWORD>] URL
	
EOF
	exit;
}

if [ -z "$1" ]; then
	usage;
fi

while getopts "u:p:" opt; do
	case "$opt" in 
	u)
		user=$OPTARG;
		((shifts++));
		;;
	p) 
		password=$OPTARG;
		((shifts++));
		;;
	\?)
		usage;
		;;
	esac;
	((shifts++));
done

for ((i=0;i<$shifts;++i)); do
	shift;
done
url="$1?format=txt";


if [ ! -z "$user" ]; then
	credentials="--user $user:$password";
fi

curl --silent $credentials $url | sed -f wiki.sed

